// Code generated by goctl. DO NOT EDIT.
package types

type GetIndexReq struct {
}

type GetIndexResp struct {
	Msg string `json:"msg"`
}

type PostIndexReq struct {
	Name string `json:"name"`
}

type PostIndexResp struct {
	Id   int64  `json:"id"`
	Name string `json:"name"`
}
